name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          echo "github.event.issue.title":${{github.event.issue.title}}
          echo "github.event.issue.body":${{github.event.issue.body}}
          echo "github.event.pull_request.title":${{github.event.pull_request.title}}
          echo "github.event.pull_request.body":${{github.event.pull_request.body}}
          echo "github.event.comment.body":${{github.event.comment.body}}
          echo "github.event.review.body":${{github.event.review.body}}
          echo "github.event.review_comment.body":${{github.event.review_comment.body}}
          echo "github.event.pages.*.page_name":${{github.event.pages.*.page_name}}
          echo "github.event.commits.*.message":${{github.event.commits.*.message}}
          echo "github.event.head_commit.message":${{github.event.head_commit.message}}
          echo "github.event.head_commit.author.email":${{github.event.head_commit.author.email}}
          echo "github.event.head_commit.author.name":${{github.event.head_commit.author.name}}
          echo "github.event.commits.*.author.email":${{github.event.commits.*.author.email}}
          echo "github.event.commits.*.author.name":${{github.event.commits.*.author.name}}
          echo "github.event.pull_request.head.ref":${{github.event.pull_request.head.ref}}
          echo "github.event.pull_request.head.label":${{github.event.pull_request.head.label}}
          echo "github.event.pull_request.head.repo.default_branch":${{github.event.pull_request.head.repo.default_branch}}
          echo "github.head_ref":${{github.head_ref}}
